Fixed incompatibility with latest python-socketio release. 

The python-socketio released a backwards incompatible change on their minor 
release. This fix addresses this and makes the code compatible with prior and
the new python-socketio version. 

https://github.com/miguelgrinberg/python-socketio/blob/main/CHANGES.md
