Bump `python-engineio` to 4.0 to make it compatible with `python-socketio` 5.0.
